apiVersion: devops.geektime.devopscamp.gk/v1
kind: Spotpool
metadata:
  labels:
    app.kubernetes.io/name: spotpool
    app.kubernetes.io/managed-by: kustomize
  name: spotpool-sample
spec:
  # TODO(user): Add fields here
  region: ap-singapore
  availabilityZone: ap-singapore-2
  instanceType: "GN7.2XLARGE32"
  minimum: 2
  maximum: 2
  subnetId: subnet-n09geves
  vpcId: vpc-o3jhu9dn
  securityGroupIds:
    - sg-dm9bzpug
  imageId: img-e734psbk
  # Ubuntu Server 24.04 LTS 公共镜像：img-mmytdhbn
  instanceChargeType: SPOTPAID
  kongGatewayIP: "43.132.182.185"
