---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - devops.geektime.devopscamp.gk
  resources:
  - spotpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.geektime.devopscamp.gk
  resources:
  - spotpools/finalizers
  verbs:
  - update
- apiGroups:
  - devops.geektime.devopscamp.gk
  resources:
  - spotpools/status
  verbs:
  - get
  - patch
  - update
