# permissions for end users to view spotpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spotpool2
    app.kubernetes.io/managed-by: kustomize
  name: spotpool-viewer-role
rules:
- apiGroups:
  - demo.aiops.org
  resources:
  - spotpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.aiops.org
  resources:
  - spotpools/status
  verbs:
  - get
