# permissions for end users to view spotpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spotpool-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spotpool
    app.kubernetes.io/part-of: spotpool
    app.kubernetes.io/managed-by: kustomize
  name: spotpool-viewer-role
rules:
- apiGroups:
  - devops.geektime.devopscamp.gk
  resources:
  - spotpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.geektime.devopscamp.gk
  resources:
  - spotpools/status
  verbs:
  - get
