# permissions for end users to view raglogpilots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: raglogpilot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: raglogpilot-viewer-role
rules:
- apiGroups:
  - log.aiops.com
  resources:
  - raglogpilots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - log.aiops.com
  resources:
  - raglogpilots/status
  verbs:
  - get
