# permissions for end users to edit predicthpas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: predicthpa-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hpa-operator
    app.kubernetes.io/part-of: hpa-operator
    app.kubernetes.io/managed-by: kustomize
  name: predicthpa-editor-role
rules:
- apiGroups:
  - hpa.aiops.com
  resources:
  - predicthpas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hpa.aiops.com
  resources:
  - predicthpas/status
  verbs:
  - get
