apiVersion: tencentcloud.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane
spec:
  credentials:
    secretRef:
      key: credentials
      name: example-creds
      namespace: crossplane
    source: Secret
