apiVersion: autoscal.aiops.org/v1
kind: Hpa
metadata:
  labels:
    app.kubernetes.io/name: hpa
    app.kubernetes.io/managed-by: kustomize
  name: hpa-sample
spec:
  scaleTarget:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  jobs:
    - name: "scale-up"
      schedule: "*/1 * * * *"   # 每分钟扩一下
      size: 3             # 扩到3个
