apiVersion: app.aiops.org/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  deployment:
    image: nginx
    replicas: 1
    port: 80
  service:
    ports:
      - port: 8080
        targetPort: 80
  ingress:
    ingressClassName: nginx
    rules:
      - host: example.foo.com
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: application-sample
                  port:
                    number: 8080
  configMap:
    data:
      key1: value1
      key2: value2
    binaryData:
      example.bin: SGVsbG8sIFdvcmxkIQ==  # Base64 编码的二进制内容
    immutable: true
